name: cypress testing

on: 
  push:

jobs:
  testingphase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install dependencies
        run: npm ci

      - name: Run on Chrome
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/first.cy.js

      - name: Merge Mochawesome JSON reports
        run: npx mochawesome-merge cypress/reports/html/.jsons/*.json > mochawesome.json

      - name: Generate HTML report
        run: npx marge mochawesome.json -f report -o cypress/reports/html

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress execution report
          path: cypress/reports/html
          retention-days: 20
