name: cypress testing

on: push

jobs:
 testingphase:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      containers: [1]
  steps:
   - name: Checkout
     uses: actions/checkout@v2
     with:
      ref: master
   - name: Install dependencies
     run: npm ci
   - name: run on chrome
     uses: cypress-io/github-action@v4
     with:
       spec: cypress/e2e/first.cy.js
   - name: upload artifacts
     uses: actions/upload-artifact@v3
     if: always()
     with:
       name: cypress execution report
       path: cypress/reports/html
       retention-days: 20
